FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive \
    GLAMA_VERSION="1.0.0"

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates curl git && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && apt-get install -y --no-install-recommends nodejs && npm install -g mcp-proxy@5.5.4 pnpm@10.14.0 && node --version && curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR="/usr/local/bin" sh && uv python install 3.12 --default --preview && ln -s $(uv python find) /usr/local/bin/python && python --version && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app

ADD https://api.github.com/repos/IvanRublev/keyphrases-mcp/git/refs/heads/ /tmp/cache_bust

RUN git clone https://github.com/IvanRublev/keyphrases-mcp . && git checkout latest

RUN (uv sync) && (uv run keyphrases-mcp-server --download-models) && (mkdir -p /app/documents)

RUN echo '#!/bin/sh' > /app/run.sh && echo 'uv run keyphrases-mcp-server -a /app/documents' >> /app/run.sh && chmod +x /app/run.sh

CMD ["mcp-proxy", "/bin/sh", "run.sh"]
